<a href="https://colab.research.google.com/github/Kirak91/kirak91.github.io/blob/master/PARE_data_Chujun_forAlbert.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Google Colab has already installed many of the commonly used libraries
# For those that are already installed, you just need to "import" the library
# For those that are not already installed (you will know from error messages)
# You need to "!pip install" the library and then "import" the library

!pip install numpy-quaternion
import quaternion
import joblib

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 60 kB 2.9 MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
  Created wheel for numpy-quaternion: filename=numpy_quaternion-2022.4.2-cp37-cp37m-linux_x86_64.whl size=158423 sha256=f00e8fd290e454834f7d3bf21c5447535706c405b3d953e31fa6693ad48d7826
  Stored in directory: /root/.cache/pip/wheels/ce/dc/f3/1b4a5e49b5590eec6fe35cc44fce61b37f599dd67468472075
Successfully built numpy-quaternion


In [ ]:
import numpy as np

In [ ]:
# Read in the data
# First you drag and drop the data file to google colab "Files" area
# Then, you will see the file once it is successfully uploaded
# Note that this file does not stay there permanently
# You will need to upload the file again everytime you restart google colab
# Once you see the file, right click, select "Copy path"
# Then paste that PATH to the code "joblib.load('PATH')"

data = joblib.load('/content/pare_output.pkl')

In [ ]:
# pkl file is a dictionary
# Check out python code for dealing with dictionary
# This specific data file is a dictionary of dictionary
# First layer is "tracks": look up what tracks mean in PARE
# Basically, it means everytime a person enter the scene (regardless of whether
# this person had already appear in the video before), PARE treats it as a
# new entry, gives it a new "track ID", and start recording their body pose data 
# To see how many "tracks" are in this dataset, check out how many keys are in
# the dictionary

data.keys()

dict_keys([1, 2, 4, 5, 6, 7, 8, 10, 11, 12, 13, 14, 19, 17, 16, 15, 20, 21, 22, 23, 24, 25, 27, 28, 29, 30, 32, 33, 36, 37, 39, 40, 42, 43, 45, 47, 48, 49, 50, 53, 55, 56, 60, 64, 63, 65, 66, 68, 73, 74, 76, 77, 78, 79, 80, 81, 82, 83, 85, 86, 87, 88, 89, 91, 94, 95, 96, 97, 98, 100, 101, 102, 103, 104, 106, 107, 111, 112, 114, 115, 116, 117, 118, 121, 120, 119, 123, 132, 136, 137, 138, 139, 141, 142, 143, 145, 148, 147, 149, 150, 151, 152, 153, 154, 155, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169])

In [ ]:
# Now as I said, this datafile is a dictionary of dictionary
# Which means, within each "track", it is a dictionary
# So, let's examine what each "track" is, let's say "track 0"

track0 = data[1]
track0

{'pred_cam': array([[4.07888031e+00, 4.40436676e-02, 7.95767605e-01],
        [4.08088779e+00, 3.92956808e-02, 7.99082518e-01],
        [4.07610941e+00, 3.95002589e-02, 7.98690081e-01],
        [4.06647301e+00, 6.82887286e-02, 7.90184259e-01],
        [4.01029253e+00, 7.54430369e-02, 7.81816244e-01],
        [3.97327518e+00, 7.30171651e-02, 7.84515798e-01],
        [4.00737000e+00, 7.25031942e-02, 7.83695281e-01],
        [3.92130756e+00, 6.91184700e-02, 7.87626147e-01],
        [3.83423758e+00, 5.16902022e-02, 7.87752748e-01],
        [3.92895794e+00, 5.92319444e-02, 7.97586322e-01],
        [3.79161119e+00, 3.80748026e-02, 7.92602658e-01],
        [3.79458666e+00, 4.05252054e-02, 7.94445753e-01],
        [3.69753838e+00, 3.72057483e-02, 7.96048403e-01],
        [3.66373205e+00, 3.89472507e-02, 7.86117435e-01],
        [3.57423925e+00, 4.57683578e-02, 7.86542594e-01],
        [3.59882641e+00, 4.94462103e-02, 7.85876036e-01],
        [3.61326933e+00, 4.94715124e-02, 7.86114037e-01],
  

In [ ]:
# As you can see, track 0 is a huge dataframe, to be precise, a dictionary
# Again, see what entries are in this dictionary by running the following code
# As you can see, in this dictionary for track 0, there are 10 entries
# such as 'pose', 'joints3d', 'joints2d', 'bboxes', 'frame_ids'

track0.keys()

dict_keys(['pred_cam', 'orig_cam', 'verts', 'pose', 'betas', 'joints3d', 'joints2d', 'smpl_joints2d', 'bboxes', 'frame_ids'])

In [ ]:
# Let's look at one of the entry in the dictionary of track0

track0['joints3d']

array([[[-0.10772619, -0.85248744, -0.07801493],
        [-0.06528984, -0.7275788 ,  0.07733327],
        [-0.23667896, -0.6286698 ,  0.07028253],
        ...,
        [-0.14387414, -0.8770176 , -0.03142026],
        [-0.01956394, -0.8799088 ,  0.04119834],
        [-0.16201125, -0.83766925,  0.06480884]],

       [[-0.10296828, -0.85250854, -0.08025662],
        [-0.05697138, -0.7288197 ,  0.07494556],
        [-0.23015875, -0.63333356,  0.07035465],
        ...,
        [-0.13778391, -0.87769806, -0.03297611],
        [-0.01148949, -0.8810432 ,  0.03626156],
        [-0.15339074, -0.8396053 ,  0.06412415]],

       [[-0.10307302, -0.8502634 , -0.07825109],
        [-0.05623712, -0.7280407 ,  0.07774418],
        [-0.22959039, -0.63252366,  0.0755949 ],
        ...,
        [-0.13721237, -0.8761605 , -0.03091304],
        [-0.01019754, -0.87935805,  0.03699946],
        [-0.15213126, -0.8392489 ,  0.06674475]],

       ...,

       [[ 0.2268336 , -0.7808658 , -0.1392959 ],
        [ 0

In [ ]:
# As you can see above, 'joints3d' is a Pandas dataframe
# You can google more about what is Pandas dataframe in Python
# Let's see the shape of this dataframe

track0['joints3d'].shape

# We will be using the 24 joints from open pose (start with op)
# https://github.com/mkocabas/PARE/blob/master/pare/utils/kp_utils.py#L342

(103, 49, 3)

In [ ]:
# As you can see above, 'joints3d' is a dataset with dimensions of 112 x 49 x 3
# 49 sounds familiar, right? They are the 49 joints
# 3 also sounds familiar, they are the x,y,z position of each joint
# but what is 112 ?
# it is how many movie frames PARE has recorded this track for
# run the following code to examine how many frames there are for this track

track0['frame_ids']

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102])

In [ ]:
# Those were excatly 112 frames
# You can double check the length of the frame_ids

track0['frame_ids'].shape

(103,)

In [ ]:
track_id = 4
# get the specific track
track = data[track_id]
  
# get the number of frames in the track
n_frame = track['frame_ids'].shape[0]
  
# get the first column of the data frame we want: frame ids
# and convert it from 1d numpy array to 2d numpy array
frameID = np.reshape(track['frame_ids'], (n_frame,1))
  
# get the second column of the data frame we want: time
timeSec = frameID * frame_rate

# get the bounding boxes, note that there are four columns cx, cy, w, h
boxes = track['bboxes']

df_output = np.concatenate((frameID, timeSec), axis=1)
df_output = np.concatenate((df_output, boxes), axis = 1)
df_output.shape # 1 column for frame Id, 1 column for time, 4 column for bounding boxes

# get the first 24 joints, note that each joint has three columns x, y, z
# note that I need an initial numpy array of n_frame x 1 to start the for loop
df_joint = np.reshape(track['joints3d'][:,0,0], (n_frame,1))
for j in range(24): # loop over the 24 joints
  for c in range(3): # loop over the 3 coordinate within each joint
    temp = np.reshape(track['joints3d'][:,j,c], (n_frame,1))
    df_joint = np.concatenate((df_joint, temp), axis=1)

# in the end, remember to discard the first column
df_output_joint = np.delete(df_joint,[0],1)

# finally, concatenate the df_output with this joint numpy array
df_output = np.concatenate((df_output, df_output_joint), axis=1)

In [ ]:
df_output.shape

(1842, 78)

In [ ]:
frame_rate = 0.04
frameID * frame_rate

array([[ 2.2 ],
       [ 2.24],
       [ 2.28],
       ...,
       [76.  ],
       [76.04],
       [76.08]])

In [ ]:
track['bboxes'].shape

(1842, 4)

In [ ]:
track['joints3d'][:,0:24,:].shape

(1842, 24, 3)

In [ ]:
for i in range(24): 
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


In [ ]:
np.array([], dtype=np.float32).reshape(0,1)

array([], shape=(0, 1), dtype=float32)

In [ ]:
df_joint = np.reshape(track['joints3d'][:,0,0], (n_frame,1))
for j in range(24): # loop over the 24 joints
  for c in range(3): # loop over the 3 coordinate within each joint
    temp = np.reshape(track['joints3d'][:,j,c], (n_frame,1))
    df_joint = np.concatenate((df_joint, temp), axis=1)

In [ ]:
df_joint

array([[ 0.11542222,  0.11542222, -0.8051702 , ...,  0.26500225,
         0.53870565,  0.20058177],
       [ 0.11626375,  0.11626375, -0.8022127 , ...,  0.264459  ,
         0.5378716 ,  0.20314698],
       [ 0.11932184,  0.11932184, -0.80869806, ...,  0.26311225,
         0.53936017,  0.20877895],
       ...,
       [-0.08924932, -0.08924932, -0.756457  , ...,  0.3885867 ,
         0.5112012 ,  0.43994418],
       [-0.09010977, -0.09010977, -0.751032  , ...,  0.41981608,
         0.5123311 ,  0.46321958],
       [-0.09152317, -0.09152317, -0.7804215 , ...,  0.5012528 ,
         0.5102532 ,  0.35279047]], dtype=float32)

In [ ]:
df_output_joint = np.delete(df_joint,[0],1)
df_output_joint.shape

(1842, 72)

In [ ]:
def track_df(track_id, frame_rate):

  # get the specific track
  track = data[track_id]
  
  # get the number of frames in the track
  n_frame = track['frame_ids'].shape[0]
  
  # get the first column of the data frame we want: frame ids
  # and convert it from 1d numpy array to 2d numpy array
  frameID = np.reshape(track['frame_ids'], (n_frame,1))
  
  # get the second column of the data frame we want: time
  timeSec = frameID * frame_rate

  # get the bounding boxes, note that there are four columns cx, cy, w, h
  boxes = track['bboxes']

  # concatenate these three columns first
  # concatenate only works for two arrays at a time
  df_output = np.concatenate((frameID, timeSec), axis=1)
  df_output = np.concatenate((df_output, boxes), axis = 1)

  # get the first 24 joints, note that each joint has three columns x, y, z
  # note that I need an initial numpy array of n_frame x 1 to start the for loop
  df_joint = np.reshape(track['joints3d'][:,0,0], (n_frame,1))
  # loop over the 24 joints
  for j in range(24): 
    # loop over the 3 coordinate within each joint
    for c in range(3): 
      temp = np.reshape(track['joints3d'][:,j,c], (n_frame,1))
      df_joint = np.concatenate((df_joint, temp), axis=1)

  # in the end, remember to discard the first column
  df_output_joint = np.delete(df_joint,[0],1)

  # finally, concatenate the df_output with this joint numpy array
  df_output = np.concatenate((df_output, df_output_joint), axis=1)

  return df_output

In [ ]:
print(track_df(4, 0.04))

[[5.50000000e+01 2.20000000e+00 3.31924272e+02 ... 2.65002251e-01
  5.38705647e-01 2.00581774e-01]
 [5.60000000e+01 2.24000000e+00 3.31507360e+02 ... 2.64459014e-01
  5.37871599e-01 2.03146979e-01]
 [5.70000000e+01 2.28000000e+00 3.34890515e+02 ... 2.63112247e-01
  5.39360166e-01 2.08778948e-01]
 ...
 [1.90000000e+03 7.60000000e+01 2.42819947e+02 ... 3.88586700e-01
  5.11201203e-01 4.39944178e-01]
 [1.90100000e+03 7.60400000e+01 2.42731136e+02 ... 4.19816077e-01
  5.12331128e-01 4.63219583e-01]
 [1.90200000e+03 7.60800000e+01 2.43218572e+02 ... 5.01252770e-01
  5.10253191e-01 3.52790475e-01]]


In [ ]:
list = [1,2,3,4,5]
list[1:]

[2, 3, 4, 5]

In [ ]:
# Define the function that assembles all the tracks of the same target
# this function takes in two arguments track_id_list which is a list of the track ids
# and the argument of frame_duraction which is the length of each frame
def target_df(track_id_list, frame_duration):
  # first, get the data frame of the first track in the track_id_list:
  track_data = track_df(track_id = track_id_list[0], frame_rate = frame_duration)
  # then, loop over and concatenate the other tracks in the track_id_list:
  for id in track_id_list[1:] : 
    track_temp = track_df(track_id = id, frame_rate = frame_duration)
    track_data = np.concatenate((track_data, track_temp), axis=0)
  return track_data

In [ ]:
# After you DEFINED the target_df function, which means you write it out in python syntax
# AND INITIATE the function, which means you press the play icon to run the code above
# You can now CALL the fucntion, which means you assign actual values to the arguments
target_df(track_id_list =[4,6,7,10,11,13,14,19,106,114,115,120], frame_duration = 0.04)


array([[ 5.50000000e+01,  2.20000000e+00,  3.31924272e+02, ...,
         2.65002251e-01,  5.38705647e-01,  2.00581774e-01],
       [ 5.60000000e+01,  2.24000000e+00,  3.31507360e+02, ...,
         2.64459014e-01,  5.37871599e-01,  2.03146979e-01],
       [ 5.70000000e+01,  2.28000000e+00,  3.34890515e+02, ...,
         2.63112247e-01,  5.39360166e-01,  2.08778948e-01],
       ...,
       [ 3.93900000e+03,  1.57560000e+02,  1.51766221e+03, ...,
        -7.57255405e-02,  4.96107996e-01, -7.88463950e-02],
       [ 3.94000000e+03,  1.57600000e+02,  1.53763932e+03, ...,
        -6.77500740e-02,  4.92163509e-01, -6.06109500e-02],
       [ 3.94100000e+03,  1.57640000e+02,  1.54617066e+03, ...,
        -5.86723089e-02,  4.86884147e-01, -3.37072611e-02]])

In [ ]:
output = target_df(track_id_list = [1,6,7,10,11,13,14,19,106,114,115,120], frame_duration = 0.04)
a = np.asarray(output) #what do these numbers mean
pd.DataFrame(a).to_csv('/content/outcome.csv') 